<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Mani" failures="0" tests="3" name="com.DataDriven.testCases.AddCustomerTest" time="11.191" errors="0" timestamp="2024-10-11T00:08:16 IST" skipped="1">
  <testcase classname="com.DataDriven.testCases.AddCustomerTest" name="addCustomerTest" time="5.802"/>
  <testcase classname="com.DataDriven.testCases.AddCustomerTest" name="addCustomerTest" time="0.005">
    <skipped/>
  </testcase> <!-- addCustomerTest -->
  <testcase classname="com.DataDriven.testCases.AddCustomerTest" name="addCustomerTest" time="5.384"/>
  <system-out>
    <![CDATA[<br>Verification failure : expected [abc] but found [xyz]<br>
<a target="_blank" href=Fri_Oct_11_00_07_53_IST_2024.jpg>Screenshot</a>
<br>
login successfully executed]]>
  </system-out>
</testsuite> <!-- com.DataDriven.testCases.AddCustomerTest -->
